CRM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from stark.service import v1
from stark11.service import v1
from app01 import views as view1
from app03 import views as view2

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^stark/', v1.site.urls),
    # 通过v1.site是实例化一个对象，并调用urls方法
    url(r'^stark11/', v1.site.urls),

    # 分页练习
    url(r'^hosts/$', view1.hosts),
    url(r'^users/$', view1.users),


    # 分页demo
    url(r'^pagination-demo/$', view2.pagination_demo),

    url(r'^app03/edit/(\d+)$', view2.edit)
]

crm05/models.py
from django.db import models


class Department(models.Model):
    """
    部门表
    市场部     1000
    销售      1001
    """
    title = models.CharField(verbose_name='部门名称', max_length=16)
    code = models.IntegerField(verbose_name='部门编号', unique=True, null=False)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """
    员工表
    """
    # auth = models.OneToOneField(verbose_name='用户权限', to=rbac_model.User)
    name = models.CharField(verbose_name='员工姓名', max_length=16)
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    email = models.EmailField(verbose_name='邮箱', max_length=64)

    depart = models.ForeignKey(verbose_name='部门', to="Department", to_field="code")

    def __str__(self):
        return self.name


class Course(models.Model):
    """
    课程表
    如：
        Linux基础
        Linux架构师
        Python自动化开发精英班
        Python自动化开发架构师班
    """
    name = models.CharField(verbose_name='课程名称', max_length=32)

    def __str__(self):
        return self.name


class School(models.Model):
    """
    校区表
    如：
        北京海淀校区
        北京昌平校区
        上海虹口校区
        广州白云山校区
    """
    title = models.CharField(verbose_name='校区名称', max_length=32)

    def __str__(self):
        return self.title


class ClassList(models.Model):
    """
    班级表
    如：
        Python全栈  面授班  5期  10000  2017-11-11  2018-5-11
    """
    school = models.ForeignKey(verbose_name='校区', to='School')
    course = models.ForeignKey(verbose_name='课程名称', to='Course')

    semester = models.IntegerField(verbose_name="班级(期)")
    price = models.IntegerField(verbose_name="学费")
    start_date = models.DateField(verbose_name="开班日期")
    graduate_date = models.DateField(verbose_name="结业日期", null=True, blank=True)
    memo = models.CharField(verbose_name='说明', max_length=256, blank=True, null=True, )
    teachers = models.ManyToManyField(verbose_name='任课老师', to='UserInfo', related_name='teach_classes',
                                      )

    tutor = models.ForeignKey(verbose_name='班主任', to='UserInfo', related_name='classes',
                              limit_choices_to={'depart': 1001})

    def __str__(self):
        return "{0}({1}期)".format(self.course.name, self.semester)


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField(verbose_name='qq', max_length=64, unique=True, help_text='QQ号必须唯一')

    name = models.CharField(verbose_name='学生姓名', max_length=16)
    gender_choices = ((1, '男'), (2, '女'))
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)

    education_choices = (
        (1, '重点大学'),
        (2, '普通本科'),
        (3, '独立院校'),
        (4, '民办本科'),
        (5, '大专'),
        (6, '民办专科'),
        (7, '高中'),
        (8, '其他')
    )
    education = models.IntegerField(verbose_name='学历', choices=education_choices, blank=True, null=True, )
    graduation_school = models.CharField(verbose_name='毕业学校', max_length=64, blank=True, null=True)
    major = models.CharField(verbose_name='所学专业', max_length=64, blank=True, null=True)

    experience_choices = [
        (1, '在校生'),
        (2, '应届毕业'),
        (3, '半年以内'),
        (4, '半年至一年'),
        (5, '一年至三年'),
        (6, '三年至五年'),
        (7, '五年以上'),
    ]
    experience = models.IntegerField(verbose_name='工作经验', blank=True, null=True, choices=experience_choices)
    work_status_choices = [
        (1, '在职'),
        (2, '无业')
    ]
    work_status = models.IntegerField(verbose_name="职业状态", choices=work_status_choices, default=1, blank=True,
                                      null=True)
    company = models.CharField(verbose_name="目前就职公司", max_length=64, blank=True, null=True)
    salary = models.CharField(verbose_name="当前薪资", max_length=64, blank=True, null=True)

    source_choices = [
        (1, "qq群"),
        (2, "内部转介绍"),
        (3, "官方网站"),
        (4, "百度推广"),
        (5, "360推广"),
        (6, "搜狗推广"),
        (7, "腾讯课堂"),
        (8, "广点通"),
        (9, "高校宣讲"),
        (10, "渠道代理"),
        (11, "51cto"),
        (12, "智汇推"),
        (13, "网盟"),
        (14, "DSP"),
        (15, "SEO"),
        (16, "其它"),
    ]
    source = models.SmallIntegerField('客户来源', choices=source_choices, default=1)
    referral_from = models.ForeignKey(
        'self',
        blank=True,
        null=True,
        verbose_name="转介绍自学员",
        help_text="若此客户是转介绍自内部学员,请在此处选择内部学员姓名",
        related_name="internal_referral"
    )
    course = models.ManyToManyField(verbose_name="咨询课程", to="Course")

    status_choices = [
        (1, "已报名"),
        (2, "未报名")
    ]
    status = models.IntegerField(
        verbose_name="状态",
        choices=status_choices,
        default=2,
        help_text=u"选择客户此时的状态"
    )
    consultant = models.ForeignKey(verbose_name="课程顾问", to='UserInfo', related_name='consultant',
                                   limit_choices_to={'depart': 1001})
    recv_date = models.DateField(verbose_name='接客时间', null=True, blank=True)
    date = models.DateField(verbose_name="咨询日期", auto_now_add=True)
    last_consult_date = models.DateField(verbose_name="最后跟进日期", auto_now_add=True)

    def __str__(self):
        return "姓名:{0},QQ:{1}".format(self.name, self.qq, )


class ConsultRecord(models.Model):
    """
    客户跟进记录
    """
    customer = models.ForeignKey(verbose_name="所咨询客户", to='Customer')
    consultant = models.ForeignKey(verbose_name="跟踪人", to='UserInfo')
    date = models.DateField(verbose_name="跟进日期", auto_now_add=True)
    note = models.TextField(verbose_name="跟进内容...")

    def __str__(self):
        return self.customer


class PaymentRecord(models.Model):
    """
    缴费记录
    """
    customer = models.ForeignKey(Customer, verbose_name="客户")

    class_list = models.ForeignKey(verbose_name="班级", to="ClassList", blank=True, null=True)

    pay_type_choices = [
        (1, "订金/报名费"),
        (2, "学费"),
        (3, "转班"),
        (4, "退学"),
        (5, "退款"),
    ]
    pay_type = models.IntegerField(verbose_name="费用类型", choices=pay_type_choices, default=1)
    paid_fee = models.IntegerField(verbose_name="费用数额", default=0)
    turnover = models.IntegerField(verbose_name="成交金额", blank=True, null=True)
    quote = models.IntegerField(verbose_name="报价金额", blank=True, null=True)
    note = models.TextField(verbose_name="备注", blank=True, null=True)
    date = models.DateTimeField(verbose_name="交款日期", auto_now_add=True)
    consultant = models.ForeignKey(verbose_name="负责老师", to='UserInfo', help_text="谁签的单就选谁")


class Student(models.Model):
    """
    学生表（已报名）
    """
    customer = models.OneToOneField(verbose_name='客户信息', to='Customer')

    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    emergency_contract = models.CharField(max_length=32, blank=True, null=True, verbose_name='紧急联系人')
    class_list = models.ManyToManyField(verbose_name="已报班级", to='ClassList', blank=True)

    company = models.CharField(verbose_name='公司', max_length=128, blank=True, null=True)
    location = models.CharField(max_length=64, verbose_name='所在区域', blank=True, null=True)
    position = models.CharField(verbose_name='岗位', max_length=64, blank=True, null=True)
    salary = models.IntegerField(verbose_name='薪资', blank=True, null=True)
    welfare = models.CharField(verbose_name='福利', max_length=256, blank=True, null=True)
    date = models.DateField(verbose_name='入职时间', help_text='格式yyyy-mm-dd', blank=True, null=True)
    memo = models.CharField(verbose_name='备注', max_length=256, blank=True, null=True)

    def __str__(self):
        return self.username


class CourseRecord(models.Model):
    """
    上课记录表
    """
    class_obj = models.ForeignKey(verbose_name="班级", to="ClassList")
    day_num = models.IntegerField(verbose_name="节次", help_text=u"此处填写第几节课或第几天课程...,必须为数字")
    teacher = models.ForeignKey(verbose_name="讲师", to='UserInfo')
    date = models.DateField(verbose_name="上课日期", auto_now_add=True)

    course_title = models.CharField(verbose_name='本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField(verbose_name='本节课程内容概要', blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField(verbose_name='本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField(verbose_name='作业描述', max_length=500, blank=True, null=True)
    exam = models.TextField(verbose_name='踩分点', max_length=300, blank=True, null=True)

    def __str__(self):
        return "{0} day{1}".format(self.class_obj, self.day_num)


class StudyRecord(models.Model):
    course_record = models.ForeignKey(verbose_name="第几天课程", to="CourseRecord")
    student = models.ForeignKey(verbose_name="学员", to='Student')
    record_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('noshow', "缺勤"),
                      ('leave_early', "早退"),
                      )
    record = models.CharField("上课纪录", choices=record_choices, default="checked", max_length=64)
    score_choices = ((100, 'A+'),
                     (90, 'A'),
                     (85, 'B+'),
                     (80, 'B'),
                     (70, 'B-'),
                     (60, 'C+'),
                     (50, 'C'),
                     (40, 'C-'),
                     (0, ' D'),
                     (-1, 'N/A'),
                     (-100, 'COPY'),
                     (-1000, 'FAIL'),
                     )
    score = models.IntegerField("本节成绩", choices=score_choices, default=-1)
    homework_note = models.CharField(verbose_name='作业评语', max_length=255, blank=True, null=True)
    note = models.CharField(verbose_name="备注", max_length=255, blank=True, null=True)

    homework = models.FileField(verbose_name='作业文件', blank=True, null=True, default=None)

crm05/views.py
from django.shortcuts import render

# Create your views here.

crm05/templates/multi_view.html
{% extends 'stark11/layout.html' %}


{% block body %}
    <h3>批量导入</h3>
    <a href="/static/multifile.xlsx">下载模版</a>
    <a href="http://127.0.0.1:8000/stark11/crm05/customer/file_down/">下载模版</a>
    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal" novalidate>
    {% csrf_token %}
        <p><input type="file" name="exfile"></p>
        <input class="btn btn-default" type="submit" value="提交">
    </form>
{% endblock %}

crm05/templates/public_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/stark11/bootstrap-3.3.7/css/bootstrap.css">
</head>
<body>
<div class="container">
    <form action="" novalidate style="margin-top: 30px">
        <table class="table table-bordered">
            <thead>
               <tr>
                <th>ID</th>
                <th>姓名</th>
                <th>QQ</th>
                <th>操作</th>
            </tr>
            </thead>
         <tbody>
         {% for row in customer_list %}
             <tr>
             <td>{{ row.id }}</td>
             <td>{{ row.name }}</td>
             <td>{{ row.qq }}</td>
             <td><a href="/stark11/crm05/customer/{{ row.id }}/competition/">抢单</a></td>
             </tr>
         {% endfor %}
         </tbody>
        </table>
    </form>
</div>
</body>
</html>

crm05/templates/score_list.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/stark11/bootstrap-3.3.7/css/bootstrap.css">
    <style>
        textarea {
            width: 300px;
            height: 60px;
        }
    </style>
</head>
<body>
<div class="container" style="margin-top: 50px">
    <form action="" method="post" novalidate>
        {% csrf_token %}
        <table class="table table-bordered">
            {% for foo in data %}
                <tr>
                    <td>{{ foo.obj.course_record }}</td>
                    <td>{{ foo.obj.student }}</td>
                    <td>{{ foo.obj.get_record_display }}</td>
                    {% for field in foo.form %}
                        <td>{{ field }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
        <input class="pull-right btn btn-primary" type="submit" value="提交">
    </form>
</div>
</body>
</html>

crm05/templates/scores_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>所在班级</h3>
<ul id="classList" sid="{{ sid }}">
    {% for obj in class_list %}
        <li cid="{{ obj.id }}">{{ obj.course.name }}({{ obj.semester }}期)</li>
    {% endfor %}
</ul>
<h3>成绩图</h3>
<div class="container" style="width: 600px; height: 400px"></div>
</body>
<script src="https://cdn.hcharts.cn/jquery/jquery-1.8.3.min.js"></script>
<script src="https://cdn.hcharts.cn/highcharts/highcharts.js"></script>
<script>
    $(function () {
        $('#classList li').click(function () {
            var cid = $(this).attr('cid');
            var sid = $('#classList').attr('sid');
            $.ajax({
                url: '/stark11/crm05/student/chart/',
                type: 'get',
                data: {'cid':cid, 'sid':sid},
                dataType: "JSON",
                success: function (data) {
                    var config = {
                            chart: {
                                type: 'column'
                            },
                            title: {
                                text: '学生成绩'
                            },
                            subtitle: {
                                text: '数据截止 2017-03，来源: <a href="https://en.wikipedia.org/wiki/List_of_cities_proper_by_population">Wikipedia</a>'
                            },
                            xAxis: {
                                type: 'category',
                                labels: {
                                    rotation: -45,
                                    style: {
                                        fontSize: '13px',
                                        fontFamily: 'Verdana, sans-serif'
                                    }
                                }
                            },
                            yAxis: {
                                min: 0,
                                title: {
                                    text: '分数'
                                }
                            },
                            legend: {
                                enabled: false
                            },
                            tooltip: {
                                pointFormat: '成绩: <b>{point.y} 百万</b>'
                            },
                            series: [{
                                name: '总人口',
                                data: [],
                                dataLabels: {
                                    enabled: true,
                                    rotation: -90,
                                    color: '#FFFFFF',
                                    align: 'right',
                                    format: '{point.y}', // one decimal
                                    y: 10, // 10 pixels down from the top
                                    style: {
                                        fontSize: '13px',
                                        fontFamily: 'Verdana, sans-serif'
                                    }
                                }
                            }]
                        };
                        config.series[0].data =arg.data;

                        //$('#container').highcharts(config);
                        Highcharts.chart('container',config);
                }
            })
        })
    })
</script>



</html>

crm05/templates/single_view.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>单条录入</title>
    <link rel="stylesheet" href="{% static 'stark11/bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'stark11/css/stark11-form.css' %}">
</head>
<body>
<div class="container form-horizontal" style="margin-top: 20px">
<h3>单条录入</h3>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10" style="position: relative; margin-bottom: 15px">
                        {{ field }}
                    <div style="background-color: red;color: white;position: absolute;font-size: 12px;left: 15px; right: 15px;">
                        {{ field.errors.0 }}
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}
        <div class="col-sm-offset-11 col-sm-1">
            <input type="submit" class="btn btn-primary" value="提交">
        </div>
    </form>
</div>
</body>
</html>

crm05/templates/user_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/stark11/bootstrap-3.3.7/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <form action="" novalidate style="margin-top: 30px">
        <table class="table table-bordered">
            <thead>
               <tr>
                <th>ID</th>
                <th>姓名</th>
                <th>QQ</th>
            </thead>
         <tbody>
         {% for row in customers %}
             <tr>
             <td>{{ row.id }}</td>
             <td>{{ row.customer }}</td>
             <td>{{ row.customer.qq }}</td>
             </tr>
         {% endfor %}
         </tbody>
        </table>
    </form>
</div>
</body>
</html>